/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jabaubo.proyecto_reservas.Interfaces;

import com.jabaubo.proyecto_reservas.Clases.Ocupacion;
import com.jabaubo.proyecto_reservas.Clases.OcupacionRender;
import java.awt.Component;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author pokem
 */
public class PanelCalendario extends javax.swing.JPanel {

    private int month;
    private int year;
    private Calendar fecha; 
    public PanelCalendario() {
        initComponents();
        month = LocalDate.now().getMonth().getValue();
        year = LocalDate.now().getYear();
    }

    public PanelCalendario(int month, int year) {
        this.month = month;
        this.year = year;
        initComponents();
        init();
    }

    public void init() {
        celdaLunes.setTitle(true);
        celdaMartes.setTitle(true);
        celdaMiercoles.setTitle(true);
        celdaJueves.setTitle(true);
        celdaViernes.setTitle(true);
        celdaSabado.setTitle(true);
        celdaDomingo.setTitle(true);
        setDate();
        cargarOcupacionPruebas();
    }

    public void setDate() {
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.MONTH, month -1);
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.DAY_OF_MONTH, 1);
        int start = calendar.get(Calendar.DAY_OF_WEEK) - 2;
        if (start < 0) {
            calendar.add(Calendar.DATE, -7);
        }
        calendar.add(Calendar.DATE, -start);
        for (Component com : panelCalendario.getComponents()) {
            CeldaCalendario c = (CeldaCalendario) com;
            if (!c.isTitle()) {
                c.setFocusPainted(true);
                c.setText(calendar.get(Calendar.DATE) + "");
                c.setDate(calendar.getTime());
                c.currentMonth(calendar.get(Calendar.MONTH) == month - 1);
                calendar.add(Calendar.DATE, 1);
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListOcupacionReservas = new JList<>();
        panelCalendario = new javax.swing.JPanel();
        celdaLunes = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaMartes = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaMiercoles = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaJueves = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaViernes = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaSabado = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaDomingo = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario8 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario9 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario10 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario11 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario12 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario13 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario14 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario15 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario16 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario17 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario18 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario19 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario20 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario21 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario22 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario23 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario24 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario25 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario26 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario27 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario28 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario29 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario30 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario31 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario32 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario33 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario34 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario35 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario36 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario37 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario38 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario39 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario40 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario41 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario42 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario43 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario44 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario45 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario46 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario47 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario48 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        celdaCalendario49 = new com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jListOcupacionReservas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jListOcupacionReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListOcupacionReservasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListOcupacionReservas);

        panelCalendario.setLayout(new java.awt.GridLayout(7, 7));

        celdaLunes.setText("Lunes");
        celdaLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celdaLunesActionPerformed(evt);
            }
        });
        panelCalendario.add(celdaLunes);

        celdaMartes.setText("Martes");
        celdaMartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celdaMartesActionPerformed(evt);
            }
        });
        panelCalendario.add(celdaMartes);

        celdaMiercoles.setText("Miercoles");
        panelCalendario.add(celdaMiercoles);

        celdaJueves.setText("Jueves");
        panelCalendario.add(celdaJueves);

        celdaViernes.setText("Viernes");
        panelCalendario.add(celdaViernes);

        celdaSabado.setText("Sábado");
        panelCalendario.add(celdaSabado);

        celdaDomingo.setText("Domingo");
        celdaDomingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celdaDomingoActionPerformed(evt);
            }
        });
        panelCalendario.add(celdaDomingo);

        celdaCalendario8.setToolTipText("");
        celdaCalendario8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario8);

        celdaCalendario9.setToolTipText("");
        celdaCalendario9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario9);

        celdaCalendario10.setToolTipText("");
        celdaCalendario10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario10);

        celdaCalendario11.setToolTipText("");
        celdaCalendario11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario11);

        celdaCalendario12.setToolTipText("");
        celdaCalendario12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario12);

        celdaCalendario13.setToolTipText("");
        celdaCalendario13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario13);

        celdaCalendario14.setToolTipText("");
        celdaCalendario14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario14);

        celdaCalendario15.setToolTipText("");
        celdaCalendario15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario15);

        celdaCalendario16.setToolTipText("");
        celdaCalendario16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario16);

        celdaCalendario17.setToolTipText("");
        celdaCalendario17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario17);

        celdaCalendario18.setToolTipText("");
        celdaCalendario18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario18);

        celdaCalendario19.setToolTipText("");
        celdaCalendario19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario19);

        celdaCalendario20.setToolTipText("");
        celdaCalendario20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario20);

        celdaCalendario21.setToolTipText("");
        celdaCalendario21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario21);

        celdaCalendario22.setToolTipText("");
        celdaCalendario22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario22);

        celdaCalendario23.setToolTipText("");
        celdaCalendario23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario23);

        celdaCalendario24.setToolTipText("");
        celdaCalendario24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario24);

        celdaCalendario25.setToolTipText("");
        celdaCalendario25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario25);

        celdaCalendario26.setToolTipText("");
        celdaCalendario26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario26);

        celdaCalendario27.setToolTipText("");
        celdaCalendario27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario27);

        celdaCalendario28.setToolTipText("");
        celdaCalendario28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario28);

        celdaCalendario29.setToolTipText("");
        celdaCalendario29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario29);

        celdaCalendario30.setToolTipText("");
        celdaCalendario30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario30);

        celdaCalendario31.setToolTipText("");
        celdaCalendario31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario31);

        celdaCalendario32.setToolTipText("");
        celdaCalendario32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario32);

        celdaCalendario33.setToolTipText("");
        celdaCalendario33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario33);

        celdaCalendario34.setToolTipText("");
        celdaCalendario34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario34);

        celdaCalendario35.setToolTipText("");
        celdaCalendario35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario35);

        celdaCalendario36.setToolTipText("");
        celdaCalendario36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario36);

        celdaCalendario37.setToolTipText("");
        celdaCalendario37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario37);

        celdaCalendario38.setToolTipText("");
        celdaCalendario38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario38);

        celdaCalendario39.setToolTipText("");
        celdaCalendario39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario39);

        celdaCalendario40.setToolTipText("");
        celdaCalendario40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario40);

        celdaCalendario41.setToolTipText("");
        celdaCalendario41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario41);

        celdaCalendario42.setToolTipText("");
        celdaCalendario42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario42);

        celdaCalendario43.setToolTipText("");
        celdaCalendario43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario43);

        celdaCalendario44.setToolTipText("");
        celdaCalendario44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario44);

        celdaCalendario45.setToolTipText("");
        celdaCalendario45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario45);

        celdaCalendario46.setToolTipText("");
        celdaCalendario46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario46);

        celdaCalendario47.setToolTipText("");
        celdaCalendario47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario47);

        celdaCalendario48.setToolTipText("");
        celdaCalendario48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario48);

        celdaCalendario49.setToolTipText("");
        celdaCalendario49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClickDia(evt);
            }
        });
        panelCalendario.add(celdaCalendario49);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("a");

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void celdaLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celdaLunesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celdaLunesActionPerformed

    private void celdaDomingoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celdaDomingoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celdaDomingoActionPerformed

    private void celdaMartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celdaMartesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_celdaMartesActionPerformed

    private void onClickDia(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClickDia
        CeldaCalendario celda = (CeldaCalendario) evt.getSource();
        System.out.println(celda.fechaFormateada());
    }//GEN-LAST:event_onClickDia

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Calendar c = Calendar.getInstance();
        c.set(Calendar.MONTH, month-1);
        c.set(Calendar.YEAR, year);
        c.add(Calendar.MONTH, 1);
        month = c.get(Calendar.MONTH)+1;
        year = c.get(Calendar.YEAR);
        switch (c.get(Calendar.MONTH)) {
            case Calendar.JANUARY:
                jLabel1.setText("Enero de " + c.get(Calendar.YEAR));
                break;
            case Calendar.FEBRUARY:
                jLabel1.setText("Febrero de " + c.get(Calendar.YEAR));
                break;
            case Calendar.MARCH:
                jLabel1.setText("Marzo de " + c.get(Calendar.YEAR));
                break;
            case Calendar.APRIL:
                jLabel1.setText("Abril de " + c.get(Calendar.YEAR));
                break;
            case Calendar.MAY:
                jLabel1.setText("Mayo de " + c.get(Calendar.YEAR));
                break;
            case Calendar.JUNE:
                jLabel1.setText("Junio de " + c.get(Calendar.YEAR));
                break;
            case Calendar.JULY:
                jLabel1.setText("Julio de " + c.get(Calendar.YEAR));
                break;
            case Calendar.AUGUST:
                jLabel1.setText("Agosto de " + c.get(Calendar.YEAR));
                break;
            case Calendar.SEPTEMBER:
                jLabel1.setText("Septiembre de " + c.get(Calendar.YEAR));
                break;
            case Calendar.OCTOBER:
                jLabel1.setText("Octubre de " + c.get(Calendar.YEAR));
                break;
            case Calendar.NOVEMBER:
                jLabel1.setText("Noviembre de " + c.get(Calendar.YEAR));
                break;
            case Calendar.DECEMBER:
                jLabel1.setText("Diciembre de " + c.get(Calendar.YEAR));
                break;
            default:
                jLabel1.setText("Error al obtener el mes");
                break;
        }
        setDate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Calendar c = Calendar.getInstance();
        c.set(Calendar.MONTH, month-1);
        c.set(Calendar.YEAR, year);
        c.add(Calendar.MONTH, -1);
        month = c.get(Calendar.MONTH)+1;
        year = c.get(Calendar.YEAR);
        switch (c.get(Calendar.MONTH)) {
            case Calendar.JANUARY:
                jLabel1.setText("Enero de " + c.get(Calendar.YEAR));
                break;
            case Calendar.FEBRUARY:
                jLabel1.setText("Febrero de " + c.get(Calendar.YEAR));
                break;
            case Calendar.MARCH:
                jLabel1.setText("Marzo de " + c.get(Calendar.YEAR));
                break;
            case Calendar.APRIL:
                jLabel1.setText("Abril de " + c.get(Calendar.YEAR));
                break;
            case Calendar.MAY:
                jLabel1.setText("Mayo de " + c.get(Calendar.YEAR));
                break;
            case Calendar.JUNE:
                jLabel1.setText("Junio de " + c.get(Calendar.YEAR));
                break;
            case Calendar.JULY:
                jLabel1.setText("Julio de " + c.get(Calendar.YEAR));
                break;
            case Calendar.AUGUST:
                jLabel1.setText("Agosto de " + c.get(Calendar.YEAR));
                break;
            case Calendar.SEPTEMBER:
                jLabel1.setText("Septiembre de " + c.get(Calendar.YEAR));
                break;
            case Calendar.OCTOBER:
                jLabel1.setText("Octubre de " + c.get(Calendar.YEAR));
                break;
            case Calendar.NOVEMBER:
                jLabel1.setText("Noviembre de " + c.get(Calendar.YEAR));
                break;
            case Calendar.DECEMBER:
                jLabel1.setText("Diciembre de " + c.get(Calendar.YEAR));
                break;
            default:
                jLabel1.setText("Error al obtener el mes");
                break;
        }
        setDate();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jListOcupacionReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListOcupacionReservasMouseClicked
        // TODO add your handling code here:
        System.err.println(jListOcupacionReservas.getSelectedValue());
    }//GEN-LAST:event_jListOcupacionReservasMouseClicked

    public void cargarOcupacionPruebas() {
        DefaultListModel<Ocupacion> lista = new DefaultListModel<>();
        Ocupacion o1 = new Ocupacion(LocalTime.NOON, 1, "hola");
        Ocupacion o2 = new Ocupacion(LocalTime.NOON, 1, "hola");
        
        lista.addElement(o1);
        lista.addElement(o2);
        jListOcupacionReservas.setModel(lista);
        jListOcupacionReservas.setCellRenderer(new OcupacionRender());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario10;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario11;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario12;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario13;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario14;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario15;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario16;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario17;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario18;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario19;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario20;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario21;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario22;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario23;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario24;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario25;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario26;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario27;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario28;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario29;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario30;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario31;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario32;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario33;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario34;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario35;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario36;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario37;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario38;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario39;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario40;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario41;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario42;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario43;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario44;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario45;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario46;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario47;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario48;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario49;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario8;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaCalendario9;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaDomingo;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaJueves;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaLunes;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaMartes;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaMiercoles;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaSabado;
    private com.jabaubo.proyecto_reservas.Interfaces.CeldaCalendario celdaViernes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Ocupacion> jListOcupacionReservas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelCalendario;
    // End of variables declaration//GEN-END:variables
}
